baseURL = "https://example.com"
languageCode = "en-in"
title = "Jughead"
copyright = "Â© Ananth Bhaskararaman"
enableGitInfo = true

# theme as module
[module]
replacements = "github.com/ananthb/jughead -> ../.."
[module.hugoVersion]
min = "0.120.0" 
extended = true
[[module.imports]]
path = "github.com/ananthb/jughead"

# Code highlighting
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Site parameters
[params]
# Choose a colour scheme from the Pico CSS palate: https://picocss.com/docs/colors.
colourScheme = "blue"
subtitle = "Portfolio and blog theme for Hugo."

description = "Demo site for Jughead, a portfolio and blog theme for Hugo."

# Display a link to the commit that built this site in your footer.
# Requires
# Your website to be publicly hosted in GitHub and
# enableGitInfo = true
siteRepo = "ananthb/jughead"  # Site GitHub repository

# Follow setup instructions at https://utteranc.es.
# Name of the GitHub repository that will store comments
# in `owner/name` format.
utterancesRepo = "ananthb/jughead"

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ananthb/jughead"
[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/me/"
[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/ananth/"
[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/ananth-bhaskararaman-2b4227316"

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1
